version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    restart: unless-stopped
    ports:
      - '6333:6333'
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - rag_network

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: Mastermind1324
    command: server /data --console-address ":9001"
    networks:
      - rag_network

  grobid:
    image: grobid/grobid:0.8.0
    ports:
      - '8070:8070'
      - '8071:8071'
    init: true
    networks:
      - rag_network
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=123
      - S3_KEY_ID=123
      - S3_ACCESS_KEY=123
      - S3_URL=minio
      - QDRANT_URL=qdrant
      - GROBID_URL=grobid
    depends_on:
      - grobid
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  qdrant_storage:
  minio_data:

networks:
  rag_network: