version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - '6333:6333'
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - rag_network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: Mastermind1324
    command: server /data --console-address ":9001"
    networks:
      - rag_network

  api:
    build: .
    container_name: api
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - rag_network

  frontend:
    build: ../RAGFrontend/.
    container_name: frontend
    volumes:
      - ../RAGFrontend/dist/ragfrontend/browser:/app/dist/ragfrontend/browser
    networks:
      - rag_network

  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - rag_network

volumes:
  qdrant_storage:
  minio_data:

networks:
  rag_network: