version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    restart: unless-stopped
    ports:
      - '6333:6333'
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - rag_network

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: Mastermind1324
    command: server /data --console-address ":9001"
    networks:
      - rag_network

  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - rag_network

  frontend:
    build: ../RAGFrontend/.
    ports :
      - "4300:80"
    networks:
      - rag_network

volumes:
  qdrant_storage:
  minio_data:

networks:
  rag_network: