[tool.ruff.lint]
select = ["I"]
combine_as_imports = true
force_single_line = false
include_trailing_comma = true
line_length = 88
multi_line_output = 3
known_first_party = ["mein_projekt"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]